version: "3"
services:
  bench:
    build: .
    networks:
      - rpcover
  memgraph:
    image: memgraph/memgraph-platform:latest
    networks:
      - rpcover
    tty: true
    ports:
      - 3333:3000
      - 3334:7687

networks:
  rpcover:
