[tool.poetry]
name = "python-a"
version = "0.1.0"
description = ""
authors = ["lincyaw <814750204@qq.com>"]
readme = "README.md"
packages = [{include = "python_a"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
